### ISSUE TITLE
How to install perl navigator?

### ISSUE THREAD

**Issue by Twix53791** [bmeneg/coc-perl#36]
Hi, 

I just had, again, a new painfull installation process on a nvim functionality... I was joyfull to have coc.nvim working straighaway on my config, I just installed a couples of LSP like `coc-sh` in 2 sec, and then, I run `:CocInstall coc-perl` on the prompt. I open a perl file and... nothing happens... I was thinking they were installed automatically like the read me says: "In the current version of coc-perl, both supported language servers are automatically installed in case you don't have it already, meaning you only need to define which server you want to enable in CoC configuration." But in fact not isn't it?

<details><summary>my (sad) story!
</summary>

I tried first the Perl Language Server. Nothing works. I realiaze in fact it is not installed, i install it from cpan and then... I run in the same bug than [this recent issue](https://github.com/perl-ide/coc-perl/issues/35) rises. I try a bit to debug, to complicate, I give up. Ok, I try pelnavigator, and... I can't figure out how to install it! There is a binary from the github, but I can't figure out how it can works, so I try the install process [for other editors](https://github.com/bscan/PerlNavigator/tree/main#installation-for-other-editors). But I am not amiliar with npm packages, I already hate them from previous bad similar experiences than this one. I am thinking than the npm installation gonna create on the computer, somewhere, a PerlNavigator folder with everything inside and the server. So I run the install process, I delete the tmp git folder and I run my fzf-fd superfast finder on the all computer to find the server.js file. Nothing. I tried then to find a tuto on the web during an hour. I did'nt find any clues. So I came back and at the end, I understood than in fact I needed to keep the perlnavigator git clone folder, it was _him_ the final folder of the "installation" which is not a real one in my mind, but anyway. SO, why it is so complicated? Why I had to loose two hours of my life just to make work a such simple feature? Just because the doc _is not enough clear_ for the "newbies" like me who are not familiar with LSPs or npm packages. I am not blaming this repo, the Perlnagator repo is no more clear in its doc, but I post here this clarification because that's the first repo where the people are gonna try to find a help in case of problem...
</details>

### The solution!

* First, follows the [the install process for "other editors"](https://github.com/bscan/PerlNavigator/tree/main#installation-for-other-editors) of perlnavigator. Git clone the repo somewhere you want te perlnavigator folder to be here, as it gonna be permanent.

* ~~Second, run `:CocInstall coc-perl` in vim~~ see: below
* ~~Third~~Second, add this in coc-settings.json via `:CocConfig`
Replace the path of server.js by your path
```json
{
  "languageserver": {
    "perlnavigator": {
      "command": "node",
      "args": [
        "/home/<user>/.config/PerlNavigator/server/out/server.js",
        "--stdio"
      ],
      "filetypes": ["perl"]
    }
  }
}
```
And it should work!

WAIT, I am not using coc-perl !! The above block of json code run perlnavigator via coc.nvim directly, it is not using the [coc-perl](https://github.com/perl-ide/coc-perl#enabling-one-server) config. In fact I can uninstall coc-perl (what I did) and the completions still works perfectly well! When I tried to install coc-config and write the piece of config code recommanded, I run in this issue:
CocLog:
```
2023-09-10T00:56:07.577 INFO (pid:148822) [configurations] - Add folder configuration from file: /home/archx/.config/.vim/coc-settings.json
2023-09-10T00:56:07.679 ERROR (pid:148822) [extension:coc-perl] - coc-perl activated, but more than one server enabled
2023-09-10T00:56:07.681 INFO (pid:148822) [plugin] - coc.nvim initialized with node: v20.5.1 after 6236
```

I tried this three syntaxes in the coc-settings.json file:
```json
{
    "perl.navigator.enable": true,
    "perl.navigator.serverPath": "/home/<user>/PerlNavigator/server/out/server.js"
}
```
```json
{
    "perlnavigator.enable": true,
    "perlnavigator.serverPath": "/home/<user>/PerlNavigator/server/out/server.js"
}
```
```json
{
  "languageserver": {
    "perlnavigator.enable": true,
    "perlnavigator.serverPath": "/home/<user>/PerlNavigator/server/out/server.js"
  }
}
```

So, at the end, what happends? I still don't know... But I arrived to make perlnavigator completions working... without coc-perl in fact... strange!

**Comment by bmeneg** [comment]
@Twix53791 thanks for the detailed report and also for the criticism, which is a really valuable one! I'll make sure to use as basis for a complete overview of our doc and possibly ping PerlNavigator and Perl::LanguageServer maintainers to do the same.

To the issue now:
First, just to give you a quick context, coc.nvim was written before nvim had its official support for language servers, but in the past releases nvim has improved quite a lot on the LSP world and one day (not really soon though) it should become the de fact standard for LSP on nvim, however, coc.nvim doesn't lag behind on features or something like that, I would even say that's the contrary :). BUT, that's why you could get PerlNavigator working without coc-perl, the first snippet you pasted is indeed to way to get PerlNavigator configured without coc.nvim.

> When I tried to install coc-config and write the piece of config code recommanded, I run in this issue:

The error message you saw in your coc log output, `... ERROR ... [extension:coc-perl] - coc-perl activated, but more than one server enabled`, means you had both PerlNavigator and Perl::LanguageServer `.enable` option set to `true` in the configuration file, eg. (using the our default notation for each server):
```json
{
    "perl.navigator.enable": true,
    "perl.p::ls.enable": true
}
```
And as said in the docs, only one must be enabled at a time, otherwise the extension will only terminate and nothing will indeed work. I could set a default "winner" for such cases, but I don't think it's fair to any of the servers. One option, though, would to give the user the option to choose one of them in case both are enabled... like in a floating window.. hmm.. I'm going to think about it.

> I was thinking they were installed automatically like the read me says: "In the current version of coc-perl, both
> supported language servers are automatically installed in case you don't have it already, meaning you only need
> to define which server you want to enable in CoC configuration." But in fact not isn't it?

Ooh, I just found where things fell off the rails... the installation process requires you to have **already** enabled one of the servers in coc-settings.json to **then** install the server you chose. For intance, after installing coc.nvim and coc-perl, the user (you) opens `:CocConfig` and add `"perl.navigator.enabled": true` or `"perl.p::ls.enable": true`, thus the next time you open a Perl file, or after a `:CocRestart`, `coc-perl` would take over and install the server you chose to enable in the coc configuration file.

Ok, I already know where to modify in the docs for getting it more clear, even more for those not aware of how LSP or CoC actually works. Also, I'll think about adding a "floating window" for the user to choose the language server he wants to use with coc-perl.

**Comment by bmeneg** [comment]
@Twix53791 PR #38 brought the fix for issue #35 and also addressed some of your concerns around documentation. Unfortunately the longer the doc gets, the less people will read it, so I made sure to make small tweaks and add a specific section related to the automatic server installation process.

EDIT: in case you think that's not enough, please feel free to reopen this issue and I'll be glad to discuss how to further improve the docs.

Now, wrt the floating window to let the user choose which server he wants, demands a more in-depth study of UI's API, even more considering VIM UI is different from NeoVIM's one. But that's something in my TODO already.

**Comment by Twix53791** [comment]
Hi, thank you @bmeneg for your deep concern with this issue! 

> Ooh, I just found where things fell off the rails... the installation process requires you to have already enabled one of the servers in coc-settings.json to then install the server you chose. 

Ok, well I understand the first problem I had. The former doc wasn't clear on this point!

> The error message you saw in your coc log output, ... ERROR ... [extension:coc-perl] - coc-perl activated, but more than one server enabled, means you had both PerlNavigator and Perl::LanguageServer .enable option set to true in the configuration file, eg. (using the our default notation for each server)

Strange, I am pretty sure I had only the lines I posted above in my coc-settings file. But maybe I had at that time, somewhere else in the vim config a line confusing things, or a typo error in the coc config file... I reinstall several times coc-perl, maybe something got wrong at some point, a cache was'nt cleared somewhere or I don't know... 

But anyway, I reinstalled everything today in exactly 36 seconds and everything works! The steps I did  1) write :CocConfig, 2) install coc-perl, 3) :CocRestart.

About the changes you did in the doc, it is better obviously, but I think it can be even better. Too verbose I think. We don't need all this explaination about the "Configurations properties", it make things look like complicated whereas they are not. If you want to keep this block, maybe put it after the "Enabling one server". I think, also, you could recommand to use perl navigator and put is as first choice. I think its less prone to bug than Perl LSP and moreover, yesterday I saw the cpan install of perl LSP, its complilation is huge! A complicated thing than this package I guess...

**Comment by bmeneg** [comment]
> Strange, I am pretty sure I had only the lines I posted above in my coc-settings file. But maybe I had at that time, 
> somewhere else in the vim config a line confusing things, or a typo error in the coc config file... I reinstall several
> times coc-perl, maybe something got wrong at some point, a cache was'nt cleared somewhere or I don't know...

Hmm, one thing I changed in the version I released yesterday was the way "workspace" CoC configuration files were being created after some options lookup/update. Maybe you had a `$workspaceFolder/.vim/coc-settings.json` in your local folder, creating by coc-perl, with one server enabled while your user config file (the one when you `:CocConfig`) had another. Idk, but...

> But anyway, I reinstalled everything today in exactly 36 seconds and everything works! The steps I did 1) write 
> :CocConfig, 2) install coc-perl, 3) :CocRestart.

I'm really glad it worked :)

Now, on the docs front... thanks once again! I'll try to reduce some of the verbosity and check where I can simplify other things. About recommending PerlNavigator, personally, I also prefer using it, but people has said that Perl::LanguageServer has a really nice integration with Perl's debugger (which PerlNavigator lacks). But I've used nvim-dap + vscode-perl-debug for integrating nvim with the debugger.
